{{- $Ingress := .Values.ingress -}}
{{- if $Ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.host  }}-rules
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host  }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-configmap
            port:
                number: 80
  tls:
  - secretName: {{ .Values.ingress.host  }}-tls
    hosts:
    - {{ .Values.ingress.host  }}
{{ end }}